# Generated by Django 5.0.3 on 2024-06-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=122)),
                ('aadhaar_no', models.CharField(max_length=12)),
                ('class_of_stud', models.CharField(max_length=20)),
                ('student_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_info',
            fields=[
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=122)),
                ('aadhaar_no', models.CharField(max_length=12)),
                ('teacher_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
