# Generated by Django 5.0.3 on 2024-06-26 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_student_info_password_teacher_info_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_class_mapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_stud', models.CharField(max_length=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.teacher_info')),
            ],
        ),
    ]
