# Generated by Django 5.0.3 on 2024-07-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_studentmarks_chemistry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=122)),
                ('subject', models.CharField(max_length=122)),
                ('message', models.CharField(max_length=122)),
            ],
        ),
    ]
